name: CI Pipeline (Tests Automatisés)

# Déclencheur : À chaque "push" sur la branche principale
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-api:
    runs-on: ubuntu-latest  # Le serveur Linux de GitHub

    steps:
    # 1. Récupérer ton code
    - name: Checkout du code
      uses: actions/checkout@v3

    # 2. Installer Python 3.12 (identique à ton Mac)
    - name: Installation de Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 3. Installer les dépendances
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Lancer les tests
    - name: Lancer Pytest
      run: |
        pytest